package com.example.aiarticlesummarizer.service;

import com.example.aiarticlesummarizer.model.Summary;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;

@Service
public class ExportService {

    public byte[] exportToPdf(Summary summary) throws IOException {
        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            
            float margin = 50;
            float yPosition = page.getMediaBox().getHeight() - margin;
            float lineHeight = 14;
            float titleFontSize = 16;
            float bodyFontSize = 11;
            float smallFontSize = 9;
            
            PDType1Font titleFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font bodyFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            PDType1Font smallFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_OBLIQUE);
            
            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                // Title
                if (summary.getArticleTitle() != null && !summary.getArticleTitle().isBlank()) {
                    contentStream.beginText();
                    contentStream.setFont(titleFont, titleFontSize);
                    contentStream.newLineAtOffset(margin, yPosition);
                    contentStream.showText(summary.getArticleTitle());
                    contentStream.endText();
                    yPosition -= (lineHeight * 2);
                }
                
                // Metadata
                contentStream.beginText();
                contentStream.setFont(smallFont, smallFontSize);
                contentStream.newLineAtOffset(margin, yPosition);
                
                if (summary.getSourceUrl() != null && !summary.getSourceUrl().isBlank()) {
                    contentStream.showText("Source: " + summary.getSourceUrl());
                    contentStream.newLineAtOffset(0, -lineHeight);
                    yPosition -= lineHeight;
                }
                if (summary.getCreatedAt() != null) {
                    String dateStr = summary.getCreatedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                    contentStream.showText("Created: " + dateStr);
                    contentStream.newLineAtOffset(0, -lineHeight);
                    yPosition -= lineHeight;
                }
                contentStream.showText("Length: " + summary.getTargetLength() + " | Model: " + summary.getModel() + " | Latency: " + summary.getLatencyMs() + "ms");
                contentStream.endText();
                yPosition -= (lineHeight * 2);
                
                // Summary content - simple approach: split by newlines
                contentStream.beginText();
                contentStream.setFont(bodyFont, bodyFontSize);
                contentStream.newLineAtOffset(margin, yPosition);
                
                String summaryText = summary.getSummary();
                String[] lines = summaryText.split("\n");
                
                for (String line : lines) {
                    if (line.trim().isEmpty()) {
                        yPosition -= lineHeight;
                        contentStream.newLineAtOffset(0, -lineHeight);
                        continue;
                    }
                    
                    // For very long lines, truncate (simplified approach)
                    String displayLine = line.length() > 100 ? line.substring(0, 100) + "..." : line;
                    contentStream.showText(displayLine);
                    yPosition -= lineHeight;
                    contentStream.newLineAtOffset(0, -lineHeight);
                    
                    // Stop if we run out of space (simplified - no page breaks)
                    if (yPosition < margin + 50) {
                        break;
                    }
                }
                contentStream.endText();
                
                // Footer
                contentStream.beginText();
                contentStream.setFont(smallFont, smallFontSize);
                contentStream.newLineAtOffset(margin, margin);
                contentStream.showText("Generated by AI Article Summarizer");
                contentStream.endText();
            }
            
            document.save(baos);
            return baos.toByteArray();
        }
    }

    public String exportToMarkdown(Summary summary) {
        StringBuilder md = new StringBuilder();

        // Title
        if (summary.getArticleTitle() != null && !summary.getArticleTitle().isBlank()) {
            md.append("# ").append(summary.getArticleTitle()).append("\n\n");
        }

        // Metadata
        md.append("## Metadata\n\n");
        if (summary.getSourceUrl() != null && !summary.getSourceUrl().isBlank()) {
            md.append("- **Source:** ").append(summary.getSourceUrl()).append("\n");
        }
        if (summary.getCreatedAt() != null) {
            String dateStr = summary.getCreatedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
            md.append("- **Created:** ").append(dateStr).append("\n");
        }
        md.append("- **Length:** ").append(summary.getTargetLength()).append("\n");
        md.append("- **Model:** ").append(summary.getModel()).append("\n");
        md.append("- **Latency:** ").append(summary.getLatencyMs()).append("ms\n\n");

        // Summary
        md.append("## Summary\n\n");
        md.append(summary.getSummary()).append("\n\n");

        // Footer
        md.append("---\n");
        md.append("*Generated by AI Article Summarizer*\n");

        return md.toString();
    }
}
